version: 2.1

jobs:
  build-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/remitdepat_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  check-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/alhassnekeita2007_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 61
  test-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/john.lindal001_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 62
  save-data-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/andris.pa_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 64

workflows:
  build:
    jobs:
      - build-app
  save-data:
    jobs:
      - save-data-app
  check:
    jobs:
      - check-app
  test:
    jobs:
      - test-app
